### ISSUE TITLE
Отключенный компонент.

### ISSUE THREAD

**Issue by Kapito000** [MeeXaSiK/NightCache#1]
Нашел интересный момент с отключением активности системы
`NightCacheInstallMachine` :
`system.SetNightCacheSystemActive(false);`
При такой реализации мы лишены возможности отключить отдельный компонент на объекте. Происходит отключение компонентов с логикой на всем объекте. Это не гибко. В классической реализации Unity отдельные компоненты отключаются т.к. являются "MonoBehaviour".
Мне, кажется было бы лучше такой функционал перенести на `NightCache`. Создать собственный аналог:
`gameObject.SomeGameComponent.enable = false/true`
 Тогда мы сможем отключать конкретный компонент. Сейчас это не возможно.

**Comment by MeeXaSiK** [comment]
SetNightCacheSystemActive(status) отвечает за то, будут ли выполнятся покадровые методы у кэшированного компонента.
Ничто не мешает отключать другие компоненты на объекте, особенно, если они красиво подвязаны через паттерн Observer
