### ISSUE TITLE
Лишний класс.

### ISSUE THREAD

**Issue by Kapito000** [MeeXaSiK/NightCache#2]
Среди классов системы обнаружил никак незадействованный класс `NightCacheInstallable`.
Его код полностью повторяет `NightInstallable`, единственное наследуется от `NightCache`.
В документации он не указан, предположительный функционал то же, пока не ясен.

**Comment by MeeXaSiK** [comment]
NightInstallable - содержит метод "OnInstall" для MonoBehaviour.
NightCacheInstallable - содержит метод "OnInstall" для NightCache.

В последнем обновлении немного по-другому и логичнее:

MonoInstallable - содержит метод "OnFirstEnable" для MonoBehaviour.
NightCacheInstallable - содержит метод "OnFirstEnable" для NightCache.
