### ISSUE TITLE
Излишнее наследование.

### ISSUE THREAD

**Issue by Kapito000** [MeeXaSiK/NightCache#3]
`NightCache` требует к себе экземпляр `NightCacheInstallMachine` в котором реализована инициализация системы. `NightCacheInstallMachine` наследуется от `NightInstallable`. 
Такое наследование можно было не делать. Объясню почему. 
Для того, что бы сторонний разработчик разобрался в описанном коде понадобится затратить немного больше времени, держать в голове лишнюю сущность (`OnInstall()` вызывается в этом классе, но по средствам наследования из родительского класса `NightInstallable`, содержащий `OnEnable` с которого по сути начинается вся "магия").
Я не против механизма наследования. Однако в конкретно взятом случае это не подходит. На лицо всего один наследник. Необходимости создавать новых наследников нет т.к. нет некой общей для нескольких других классов сущности. Нет необходимости, что-то спрятать для удобного использования в другом месте. Код стал чуть-чуть сложнее для восприятия.

**Comment by MeeXaSiK** [comment]
Не вижу здесь ничего страшного в наследовании, но спасибо за замечание насчёт метода "OnInstall". Сейчас я переименовал его на "OnFirstEnable", что куда логичнее :)
